registry: fix bottleneck in registering resources
bbc/nmos-node pull request #15
Opened 2018-08-03 15:33 UTC by andrewbonney

A historic case of not thinking it through. Every time a resource was registered with the Node API it enumerated a full dictionary of all resources of that type. All that was necessary was to check how many there were. This avoids registrations getting progressively slower.

2018-08-06 16:38 UTC, simonrankine requested changes

2018-08-06 16:38 UTC, simonrankine commented on nmosnode/registry.py
> +            return RES_UNSUPPORTED
It looks like you repeat this check? Exactly the same code appears on lines 472 and 473. It does seem slightly odd that a method for checking the length of something checks it's validity? I guess if we were being super "Pythonic" this shouldn't be "checked" at all, but instead you should just try accessing something at "type" and do a try catch to see if it fails.

2018-08-06 16:38 UTC, simonrankine commented on nmosnode/registry.py
> +        items = self._len_resource(type)
Being super picky here, but if you do end up making some tweaks could this be "numItems" or something to that effect?

2018-08-07 08:23 UTC, andrewbonney commented
Hopefully that's better

2018-08-07 09:51 UTC, simonrankine approved these changes

2018-08-07 09:52 UTC, merged