Add Python 3 Debian build
bbc/nmos-node pull request #9
Opened 2018-05-11 11:55 UTC by samdnic

This adds a `python3-nodefacade` package to the Debian build automation. Not that it's a huge amount of use, since `python3-nmoscommon` doesn't pull its dependencies in properly, and `python3-pybojour` is just broken.
Will build on Jenkins if configured on one of the `pbuilder-xenial-amd64` slaves - some of the `pbuilder-xenial` ones (notably jenkins-slave-acbuild.rd...) don't have python3-setuptools.

2018-05-11 15:42 UTC, andrewbonney reviewed
LGTM. Have you tried installing it at all having built a package locally?

2018-05-14 15:50 UTC, samdnic commented
I've installed it locally and that all seems to work; but given `python3-pybonjour` is broken and there's no `python3-avahi` it's difficult to meaningfully test. Should this one go on the back burner pending that stuff being sorted? Shall I delete the PR or leave it open for now?

2018-05-14 15:53 UTC, andrewbonney commented
I'd leave it open. I've added a needs work label even though it's technically work in the dependency: https://github.com/bbc/nmos-common/pull/8

2018-11-06 16:18 UTC, simonrankine requested changes

2018-11-06 16:18 UTC, simonrankine commented on debian/control
> -Recommends: lldpd, python-nmoscommon, ips-reverseproxy-common, python-mdnsbridge
For annoying reasons the joint-ri currently needs python-nmoscommon to be in recommends not depends... I'm aware this is an issue but until I have time to sort it out it needs to stay where it is please :)

2019-04-03 12:47 UTC, closed without merging